title: dlguswo333's Blog
description: 이현재의 블로그
author: 이현재
avatar: https://github.com/dlguswo333.png
email: dlguswo002@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
excerpt_seperator:  <!--more-->

# Jekyll SEO Tag (Optional)
# =========================
logo: https://github.com/dlguswo333.png
social:
  name: 이현재, Lee Hyeonjae
  links:
    - https://github.com/dlguswo333
google_site_verification: google68ae6a4081035461.html
lang: kor
